[
    {
      "first_name": "John",
      "middle_name": "A.",
      "last_name": "Doe",
      "student_email": "john.doe1@gmail.com",
      "student_phone": "555-1234",
      "blood_group": "O+",
      "date_of_birth": "2002-04-15",
      "gender": "Male",
      "image": "https://example.com/images/john.jpg",
      "guardian_name": "Jane Doe",
      "guardian_phone": "555-5678",
      "address": "123 Elm Street",
      "department": "Computer Science",
      "semester": "Fall",
      "admission_year": "2023"
    },
    {
      "first_name": "Emily",
      "middle_name": "B.",
      "last_name": "Smith",
      "student_email": "emily.smith1@gmail.com",
      "student_phone": "555-2234",
      "blood_group": "A-",
      "date_of_birth": "2001-11-21",
      "gender": "Female",
      "image": "https://example.com/images/emily.jpg",
      "guardian_name": "Mark Smith",
      "guardian_phone": "555-6789",
      "address": "456 Oak Street",
      "department": "Business Administration",
      "semester": "Spring",
      "admission_year": "2022"
    },
    {
      "first_name": "Michael",
      "middle_name": "C.",
      "last_name": "Johnson",
      "student_email": "michael.johnson1@gmail.com",
      "student_phone": "555-3234",
      "blood_group": "B+",
      "date_of_birth": "2003-07-30",
      "gender": "Male",
      "image": "https://example.com/images/michael.jpg",
      "guardian_name": "Susan Johnson",
      "guardian_phone": "555-7890",
      "address": "789 Pine Street",
      "department": "Mechanical Engineering",
      "semester": "Fall",
      "admission_year": "2023"
    },
    {
      "first_name": "Sophia",
      "middle_name": "D.",
      "last_name": "Brown",
      "student_email": "sophia.brown1@gmail.com",
      "student_phone": "555-4234",
      "blood_group": "AB+",
      "date_of_birth": "2002-01-10",
      "gender": "Female",
      "image": "https://example.com/images/sophia.jpg",
      "guardian_name": "David Brown",
      "guardian_phone": "555-8901",
      "address": "101 Maple Street",
      "department": "Psychology",
      "semester": "Spring",
      "admission_year": "2022"
    },
    {
      "first_name": "Liam",
      "middle_name": "E.",
      "last_name": "Williams",
      "student_email": "liam.williams1@gmail.com",
      "student_phone": "555-5234",
      "blood_group": "O-",
      "date_of_birth": "2001-09-05",
      "gender": "Male",
      "image": "https://example.com/images/liam.jpg",
      "guardian_name": "Olivia Williams",
      "guardian_phone": "555-9012",
      "address": "202 Cedar Street",
      "department": "Mathematics",
      "semester": "Summer",
      "admission_year": "2021"
    },
    {
      "first_name": "Isabella",
      "middle_name": "F.",
      "last_name": "Martinez",
      "student_email": "isabella.martinez1@gmail.com",
      "student_phone": "555-6234",
      "blood_group": "A+",
      "date_of_birth": "2003-05-17",
      "gender": "Female",
      "image": "https://example.com/images/isabella.jpg",
      "guardian_name": "Carlos Martinez",
      "guardian_phone": "555-0123",
      "address": "303 Birch Street",
      "department": "Civil Engineering",
      "semester": "Fall",
      "admission_year": "2023"
    },
    {
      "first_name": "Noah",
      "middle_name": "G.",
      "last_name": "Garcia",
      "student_email": "noah.garcia1@gmail.com",
      "student_phone": "555-7234",
      "blood_group": "B-",
      "date_of_birth": "2002-12-22",
      "gender": "Male",
      "image": "https://example.com/images/noah.jpg",
      "guardian_name": "Maria Garcia",
      "guardian_phone": "555-1234",
      "address": "404 Spruce Street",
      "department": "Electrical Engineering",
      "semester": "Spring",
      "admission_year": "2022"
    },
    {
      "first_name": "Ava",
      "middle_name": "H.",
      "last_name": "Rodriguez",
      "student_email": "ava.rodriguez1@gmail.com",
      "student_phone": "555-8234",
      "blood_group": "AB-",
      "date_of_birth": "2001-06-29",
      "gender": "Female",
      "image": "https://example.com/images/ava.jpg",
      "guardian_name": "Pedro Rodriguez",
      "guardian_phone": "555-2345",
      "address": "505 Ash Street",
      "department": "Biology",
      "semester": "Summer",
      "admission_year": "2021"
    },
    {
      "first_name": "William",
      "middle_name": "I.",
      "last_name": "Lee",
      "student_email": "william.lee1@gmail.com",
      "student_phone": "555-9234",
      "blood_group": "O+",
      "date_of_birth": "2003-03-12",
      "gender": "Male",
      "image": "https://example.com/images/william.jpg",
      "guardian_name": "Jennifer Lee",
      "guardian_phone": "555-3456",
      "address": "606 Walnut Street",
      "department": "Philosophy",
      "semester": "Fall",
      "admission_year": "2023"
    },
    {
      "first_name": "Olivia",
      "middle_name": "J.",
      "last_name": "Kim",
      "student_email": "olivia.kim1@gmail.com",
      "student_phone": "555-10234",
      "blood_group": "A-",
      "date_of_birth": "2001-08-18",
      "gender": "Female",
      "image": "https://example.com/images/olivia.jpg",
      "guardian_name": "Henry Kim",
      "guardian_phone": "555-4567",
      "address": "707 Fir Street",
      "department": "Chemistry",
      "semester": "Spring",
      "admission_year": "2022"
    }
  ]
  